language: python

virtualenv:
    system_site_packages: true

python:
  - "2.6"
  - "2.7"
  - "pypy"

before_install:
 - sudo apt-get install yum

install:
  - pip install pybuilder
  - pyb install_dependencies

script: "pyb --debug -v"
